package mms

type MmsType int

const (
	MMS_ARRAY MmsType = iota
	MMS_STRUCTURE
	MMS_BOOLEAN
	MMS_BIT_STRING
	MMS_INTEGER
	MMS_UNSIGNED
	MMS_FLOAT
	MMS_OCTET_STRING
	MMS_VISIBLE_STRING
	MMS_GENERALIZED_TIME
	MMS_BINARY_TIME
	MMS_BCD
	MMS_OBJ_ID
	MMS_MMS_STRING
	MMS_UTC_TIME
	MMS_DATA_ACCESS_ERROR
)

type MmsDataAccessError int

const (
	DATA_ACCESS_ERROR_SUCCESS_NO_UPDATE = iota - 3
	DATA_ACCESS_ERROR_NO_RESPONSE
	DATA_ACCESS_ERROR_SUCCESS
	DATA_ACCESS_ERROR_OBJECT_INVALIDATED
	DATA_ACCESS_ERROR_HARDWARE_FAULT
	DATA_ACCESS_ERROR_TEMPORARILY_UNAVAILABLE
	DATA_ACCESS_ERROR_OBJECT_ACCESS_DENIED
	DATA_ACCESS_ERROR_OBJECT_UNDEFINED
	DATA_ACCESS_ERROR_INVALID_ADDRESS
	DATA_ACCESS_ERROR_TYPE_UNSUPPORTED
	DATA_ACCESS_ERROR_TYPE_INCONSISTENT
	DATA_ACCESS_ERROR_OBJECT_ATTRIBUTE_INCONSISTENT
	DATA_ACCESS_ERROR_OBJECT_ACCESS_UNSUPPORTED
	DATA_ACCESS_ERROR_OBJECT_NONE_EXISTENT
	DATA_ACCESS_ERROR_OBJECT_VALUE_INVALID
	DATA_ACCESS_ERROR_UNKNOWN
)

type MmsValue struct {
	valueType   MmsType
	deleteValue byte
	value       any
}

type structure struct {
	size       int
	components []*MmsValue
}

type Asn1PrimitiveValue_pointer *Asn1PrimitiveValue

type octetString struct {
	maxSize int
	buf     []byte
}

type bitString struct {
	buf []byte
}

type visibleString string

type utcTime [8]byte

type binaryTime [6]byte
