definitions:
  service.AuditLog:
    properties:
      create_time:
        type: string
      id:
        type: integer
      message:
        type: string
    type: object
  service.DataAttribute:
    properties:
      created_at:
        type: string
      data_object_id:
        type: integer
      data_source:
        type: string
      id:
        type: integer
      iec61850_ref:
        type: string
      name:
        type: string
      updated_at:
        type: string
      value:
        type: string
    type: object
  service.DataObject:
    properties:
      dataAttribute:
        items:
          $ref: '#/definitions/service.DataAttribute'
        type: array
      description:
        type: string
      id:
        type: integer
      logicalNodeID:
        type: integer
      name:
        type: string
    type: object
  service.IEC61850Model:
    properties:
      description:
        type: string
      id:
        type: integer
      logicalDevice:
        items:
          $ref: '#/definitions/service.LogicalDevice'
        type: array
      name:
        type: string
    type: object
  service.LogicalDevice:
    properties:
      description:
        type: string
      id:
        type: integer
      logicalNode:
        items:
          $ref: '#/definitions/service.LogicalNode'
        type: array
      modelID:
        type: integer
      name:
        type: string
    type: object
  service.LogicalNode:
    properties:
      id:
        type: integer
      logicalDeviceID:
        type: integer
      name:
        type: string
    type: object
  service.MappingRule:
    properties:
      create_time:
        type: string
      id:
        type: integer
      iec61850_ref:
        type: string
      station_id:
        type: integer
      type:
        type: string
      update_time:
        type: string
    type: object
  service.ModbusDetail:
    properties:
      id:
        type: integer
      rule_id:
        type: integer
    type: object
  service.MqttDetail:
    properties:
      id:
        type: integer
      rule_id:
        type: integer
    type: object
  service.Station:
    properties:
      configs:
        additionalProperties: {}
        type: object
      handlers:
        additionalProperties: {}
        type: object
      host:
        type: string
      id:
        type: integer
      name:
        type: string
      port:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/audit_log/{id}:
    get:
      parameters:
      - description: Audit log ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.AuditLog'
      summary: Get audit log by ID
      tags:
      - AuditLog
  /api/v1/iec61850/data_object/{id}:
    get:
      parameters:
      - description: DataObject ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.DataObject'
      summary: Get DataObject by ID
      tags:
      - IEC61850
  /api/v1/iec61850/data_object/{object_id}/node:
    get:
      parameters:
      - description: DataObject ID
        in: path
        name: object_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.DataAttribute'
            type: array
      summary: Get Nodes by DataObject ID
      tags:
      - IEC61850
  /api/v1/iec61850/model/{id}:
    get:
      parameters:
      - description: IEC61850 model ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.IEC61850Model'
      summary: Get IEC61850 model by ID
      tags:
      - IEC61850
  /api/v1/iec61850/node/{id}:
    get:
      parameters:
      - description: Node ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.DataAttribute'
      summary: Get Node by ID
      tags:
      - IEC61850
  /api/v1/iec61850/node/{id}/data_source:
    put:
      consumes:
      - application/json
      parameters:
      - description: Node ID
        in: path
        name: id
        required: true
        type: integer
      - description: DataSource
        in: body
        name: dataSource
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update DataSource of a Node
      tags:
      - IEC61850
  /api/v1/iec61850/node/ref/{ref}:
    get:
      parameters:
      - description: IEC61850 reference
        in: path
        name: ref
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.DataAttribute'
      summary: Get Node by IEC61850 reference
      tags:
      - IEC61850
  /api/v1/mapping_rules/{id}:
    delete:
      parameters:
      - description: MappingRule ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: Delete a MappingRule
      tags:
      - MappingRule
    get:
      parameters:
      - description: MappingRule ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.MappingRule'
      summary: Get a MappingRule by ID
      tags:
      - MappingRule
    put:
      parameters:
      - description: MappingRule ID
        in: path
        name: id
        required: true
        type: integer
      - description: MappingRule
        in: body
        name: rule
        required: true
        schema:
          $ref: '#/definitions/service.MappingRule'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.MappingRule'
      summary: Update a MappingRule
      tags:
      - MappingRule
  /api/v1/modbus_detail/{ruleID}:
    get:
      parameters:
      - description: Rule ID
        in: path
        name: ruleID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.ModbusDetail'
      summary: Get ModbusDetail by RuleID
      tags:
      - ModbusDetail
  /api/v1/mqtt_detail/{ruleID}:
    get:
      parameters:
      - description: Rule ID
        in: path
        name: ruleID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.MqttDetail'
      summary: Get MqttDetail by RuleID
      tags:
      - MqttDetail
  /api/v1/stations:
    get:
      description: List all stations
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.Station'
            type: array
      summary: List all stations
    post:
      description: Create station
      parameters:
      - description: Station
        in: body
        name: station
        required: true
        schema:
          $ref: '#/definitions/service.Station'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Station'
      summary: Create station
  /api/v1/stations/{station_id}:
    delete:
      description: Delete station by ID
      parameters:
      - description: Station ID
        in: path
        name: station_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Station'
      summary: Delete station by ID
    get:
      description: Get station by ID
      parameters:
      - description: Station ID
        in: path
        name: station_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Station'
      summary: Get station by ID
    put:
      description: Update station by ID
      parameters:
      - description: Station ID
        in: path
        name: station_id
        required: true
        type: integer
      - description: Station
        in: body
        name: station
        required: true
        schema:
          $ref: '#/definitions/service.Station'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Station'
      summary: Update station by ID
  /api/v1/stations/{stationID}/mapping_rules:
    get:
      parameters:
      - description: Station ID
        in: path
        name: stationID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.MappingRule'
            type: array
      summary: List all MappingRule for a station
      tags:
      - MappingRule
  /audit_log:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.AuditLog'
            type: array
      summary: Get all audit logs
      tags:
      - AuditLog
swagger: "2.0"
